apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client
  name: client
spec:
  containers:
  - image: busybox
    name: client
    resources: {}
    command:
      - /bin/bash
      - -c
      - while true; do sleep 3600; done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
